<?php

namespace Toinou\SummernoteBundle\Repository;

/**
 * SummernoteImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SummernoteImageRepository extends \Doctrine\ORM\EntityRepository
{
}
